"""English conversation practice scenarios."""

CONVERSATIONS = [
  {
    "title": "At a Restaurant",
    "description": "Practice ordering food and interacting with a waiter.",
    "dialogue": [
      ("Waiter", "Good evening! Welcome to The Garden Bistro. Table for two?"),
      ("You", "Yes, please. Do you have a table by the window?"),
      ("Waiter", "Of course! Right this way. Here are your menus."),
      ("You", "Thank you. What do you recommend today?"),
      ("Waiter", "Our chef's special is grilled salmon with vegetables. It's very popular."),
      ("You", "That sounds delicious. I'll have that, please."),
      ("Waiter", "Excellent choice! And what would you like to drink?"),
      ("You", "I'd like a glass of water and an orange juice, please."),
      ("Waiter", "Sure thing. I'll be right back with your drinks."),
      ("You", "Excuse me, could I also get the dessert menu later?"),
      ("Waiter", "Absolutely! I'll bring it after your main course."),
      ("You", "Great, thank you very much!"),
    ],
    "key_phrases": [
      "Table for two, please.",
      "What do you recommend?",
      "I'll have that, please.",
      "Could I get the menu?",
      "Check, please.",
    ],
  },
  {
    "title": "At the Airport",
    "description": "Practice checking in for a flight and going through security.",
    "dialogue": [
      ("Agent", "Good morning. May I see your passport and booking confirmation?"),
      ("You", "Sure, here you go."),
      ("Agent", "Thank you. Are you checking any luggage today?"),
      ("You", "Yes, I have one suitcase to check in."),
      ("Agent", "Please place it on the scale. It's 20 kilograms — that's within the limit."),
      ("You", "Great. Can I get a window seat, please?"),
      ("Agent", "Let me check... Yes, seat 14A is available. Here's your boarding pass."),
      ("You", "Thank you. What gate do I go to?"),
      ("Agent", "Gate B12. Boarding starts at 10:30 AM."),
      ("You", "And where is the security checkpoint?"),
      ("Agent", "Go straight ahead and turn left. You'll see the signs."),
      ("You", "Perfect, thank you for your help!"),
    ],
    "key_phrases": [
      "Here's my passport.",
      "I have one bag to check in.",
      "Can I get a window seat?",
      "What gate is my flight?",
      "What time does boarding start?",
    ],
  },
  {
    "title": "Job Interview",
    "description": "Practice answering common job interview questions.",
    "dialogue": [
      ("Interviewer", "Thank you for coming in today. Please, have a seat."),
      ("You", "Thank you for the opportunity. I'm excited to be here."),
      ("Interviewer", "So, tell me a little about yourself."),
      ("You", "I have three years of experience in marketing. I enjoy working on creative campaigns and analyzing data to improve results."),
      ("Interviewer", "That's great. Why are you interested in this position?"),
      ("You", "I admire your company's innovative approach, and I believe my skills would be a great fit for your team."),
      ("Interviewer", "What would you say is your greatest strength?"),
      ("You", "I'm very organized and I pay close attention to detail. I always make sure projects are completed on time."),
      ("Interviewer", "Can you tell me about a challenge you've faced at work?"),
      ("You", "In my previous role, we had a tight deadline for a major campaign. I organized the team and we delivered it two days early."),
      ("Interviewer", "Impressive. Do you have any questions for us?"),
      ("You", "Yes, what does a typical day look like for this role?"),
    ],
    "key_phrases": [
      "Tell me about yourself.",
      "Why are you interested in this position?",
      "What is your greatest strength?",
      "Do you have any questions for us?",
      "When can you start?",
    ],
  },
  {
    "title": "At the Doctor's Office",
    "description": "Practice describing symptoms and understanding medical advice.",
    "dialogue": [
      ("Doctor", "Hello, what brings you in today?"),
      ("You", "I've been feeling unwell for the past few days. I have a sore throat and a headache."),
      ("Doctor", "I see. Do you have a fever or any other symptoms?"),
      ("You", "I had a slight fever yesterday, but it went down. I also feel very tired."),
      ("Doctor", "Let me take a look. Open your mouth and say 'ah'."),
      ("You", "Ah..."),
      ("Doctor", "Your throat is a bit red. It looks like you have a mild infection."),
      ("You", "Is it serious? Do I need antibiotics?"),
      ("Doctor", "No, it's not serious. I'll prescribe some medicine for the pain and inflammation."),
      ("You", "How often should I take the medicine?"),
      ("Doctor", "Take one tablet twice a day after meals. Drink plenty of fluids and rest."),
      ("You", "Thank you, Doctor. When should I come back if it doesn't improve?"),
    ],
    "key_phrases": [
      "I've been feeling unwell.",
      "I have a sore throat.",
      "Do I need a prescription?",
      "How often should I take this?",
      "When should I come back?",
    ],
  },
  {
    "title": "Shopping for Clothes",
    "description": "Practice asking about sizes, prices, and trying on clothes.",
    "dialogue": [
      ("You", "Hi, I'm looking for a jacket. Do you have any on sale?"),
      ("Clerk", "Yes! We have a great selection over here. What size are you?"),
      ("You", "I'm usually a medium. Can I try this blue one?"),
      ("Clerk", "Of course! The fitting rooms are right over there."),
      ("You", "Thanks. Hmm, this one is a bit tight. Do you have a large?"),
      ("Clerk", "Let me check... Here you go. Try this one."),
      ("You", "This fits much better! How much is it?"),
      ("Clerk", "It's normally $80, but it's 25% off today, so it's $60."),
      ("You", "That's a great deal. I'll take it."),
      ("Clerk", "Would you like anything else? We also have matching scarves."),
      ("You", "No, thanks. Just the jacket. Can I pay by card?"),
      ("Clerk", "Absolutely. I'll ring that up for you at the register."),
    ],
    "key_phrases": [
      "Do you have this in a different size?",
      "Can I try this on?",
      "How much does this cost?",
      "Is this on sale?",
      "Can I pay by card?",
    ],
  },
  {
    "title": "Asking for Directions",
    "description": "Practice asking for and understanding directions in a city.",
    "dialogue": [
      ("You", "Excuse me, could you help me? I'm looking for the nearest subway station."),
      ("Stranger", "Sure! Go straight for two blocks, then turn right on Oak Street."),
      ("You", "Turn right on Oak Street. Got it. Is it far from here?"),
      ("Stranger", "Not at all. It's about a five-minute walk."),
      ("You", "Great. And do you know if there's a pharmacy nearby?"),
      ("Stranger", "Yes, there's one right next to the subway station, actually."),
      ("You", "Perfect. Is it on the left side or the right side of the street?"),
      ("Stranger", "It's on the left side. You can't miss it — there's a big green sign."),
      ("You", "Thank you so much! One more question — is there a good coffee shop around here?"),
      ("Stranger", "There's a nice one called Bean & Brew on the corner of Oak and 5th."),
      ("You", "Wonderful. Thanks for all your help!"),
      ("Stranger", "No problem! Have a great day!"),
    ],
    "key_phrases": [
      "Excuse me, could you help me?",
      "How do I get to...?",
      "Is it far from here?",
      "Turn left / Turn right.",
      "Go straight for two blocks.",
    ],
  },
  {
    "title": "Hotel Check-in",
    "description": "Practice checking into a hotel and asking about amenities.",
    "dialogue": [
      ("You", "Hello, I have a reservation under the name Smith."),
      ("Receptionist", "Welcome, Mr. Smith! Let me pull up your booking. Yes, a double room for three nights."),
      ("You", "That's correct. Is breakfast included?"),
      ("Receptionist", "Yes, breakfast is served from 7 to 10 AM in the restaurant on the ground floor."),
      ("You", "Wonderful. What floor is my room on?"),
      ("Receptionist", "You're on the 5th floor, room 512. Here's your key card."),
      ("You", "Thank you. Is there Wi-Fi available?"),
      ("Receptionist", "Yes, free Wi-Fi in all rooms. The password is on the card in your room."),
      ("You", "Great. And what time is checkout?"),
      ("Receptionist", "Checkout is at 11 AM. You can request a late checkout at the front desk."),
      ("You", "Is there a gym or a pool in the hotel?"),
      ("Receptionist", "Yes, the gym is on the 2nd floor and the pool is on the rooftop. Both open at 6 AM."),
    ],
    "key_phrases": [
      "I have a reservation under...",
      "Is breakfast included?",
      "What time is checkout?",
      "Is there Wi-Fi available?",
      "Can I get a late checkout?",
    ],
  },
  {
    "title": "Making Friends",
    "description": "Practice casual conversation and getting to know someone.",
    "dialogue": [
      ("New friend", "Hi! I don't think we've met. I'm Alex."),
      ("You", "Nice to meet you, Alex! I'm Sam. Are you from around here?"),
      ("New friend", "I actually just moved here from Chicago. What about you?"),
      ("You", "I've been living here for about five years. You'll love it here!"),
      ("New friend", "I hope so! What do you do for work?"),
      ("You", "I work as a graphic designer. How about you?"),
      ("New friend", "I'm a software engineer. I just started at a new company downtown."),
      ("You", "That's awesome! What do you like to do for fun?"),
      ("New friend", "I love hiking and photography. Do you have any hobbies?"),
      ("You", "I enjoy painting and cooking. We should hang out sometime!"),
      ("New friend", "Definitely! Want to grab coffee this weekend?"),
      ("You", "Sounds great! Let me give you my number."),
    ],
    "key_phrases": [
      "Nice to meet you!",
      "Where are you from?",
      "What do you do for work?",
      "What do you like to do for fun?",
      "We should hang out sometime!",
    ],
  },
  {
    "title": "Phone Call - Making an Appointment",
    "description": "Practice making appointments over the phone.",
    "dialogue": [
      ("Receptionist", "Good morning, Sunshine Dental Clinic. How can I help you?"),
      ("You", "Hi, I'd like to make an appointment for a dental checkup."),
      ("Receptionist", "Sure. Have you been to our clinic before?"),
      ("You", "No, this would be my first visit."),
      ("Receptionist", "No problem. I'll need your full name and phone number."),
      ("You", "My name is Jordan Lee, and my number is 555-0123."),
      ("Receptionist", "Thank you. When would you like to come in?"),
      ("You", "Do you have anything available next Tuesday afternoon?"),
      ("Receptionist", "Let me check... We have an opening at 2:30 PM. Does that work?"),
      ("You", "That's perfect. How long will the appointment take?"),
      ("Receptionist", "About 45 minutes for a first visit. Please arrive 10 minutes early to fill out forms."),
      ("You", "Got it. Thank you very much! See you Tuesday."),
    ],
    "key_phrases": [
      "I'd like to make an appointment.",
      "Do you have any availability on...?",
      "What time works best?",
      "How long will it take?",
      "Can I reschedule?",
    ],
  },
  {
    "title": "At the Bank",
    "description": "Practice common banking conversations.",
    "dialogue": [
      ("You", "Hello, I'd like to open a savings account."),
      ("Teller", "Of course! Do you have an ID with you?"),
      ("You", "Yes, here's my driver's license."),
      ("Teller", "Thank you. We have two types of savings accounts. One has a higher interest rate but requires a minimum balance."),
      ("You", "What's the minimum balance for that one?"),
      ("Teller", "It's $500. The interest rate is 2.5% per year."),
      ("You", "That sounds good. I'll go with that option."),
      ("Teller", "Great. How much would you like to deposit today?"),
      ("You", "I'd like to deposit $1,000 to start."),
      ("Teller", "Perfect. Would you also like to set up online banking?"),
      ("You", "Yes, please. That would be very convenient."),
      ("Teller", "All set! Here's your account information and temporary PIN."),
    ],
    "key_phrases": [
      "I'd like to open an account.",
      "What's the interest rate?",
      "I'd like to make a deposit.",
      "Can I set up online banking?",
      "What are the fees?",
    ],
  },
]


def get_all_conversations():
  """Return list of all conversation scenarios."""
  return CONVERSATIONS


def get_conversation_titles():
  """Return list of conversation titles."""
  return [c["title"] for c in CONVERSATIONS]


def get_conversation_by_index(index):
  """Return a conversation by its index."""
  if 0 <= index < len(CONVERSATIONS):
    return CONVERSATIONS[index]
  return None
